name: Build and push Docker Image to DockerHub

on:
  push:
    branches:
      - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        commit_message=$(echo "${{ github.event.head_commit.message }}" | tr -d '[:space:]')
        docker build . --file Dockerfile --tag stachu420/sgalekcom-frontend:${commit_message}
    
    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push the Docker image to DockerHub
      run: |
        commit_message=$(echo "${{ github.event.head_commit.message }}" | tr -d '[:space:]')
        docker push stachu420/sgalekcom-frontend:${commit_message}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Set up Kubernetes context
      uses: azure/setup-kubectl@v1
      with:
        kubeconfig: ${{ secrets.KUBE_CONFIG }}

    - name: Deploy to Kubernetes
      run: |
        kubectl set image deployment/sgalekcom-frontend sgalekcom-frontend=stachu420/sgalekcom-frontend:${{ github.event.head_commit.message }}
        kubectl rollout status deployment/sgalekcom-frontend

